const ADD_MOVIE = 'ADD_MOVIE'
const ADD_MOVIES = 'ADD_MOVIES'
const ADD_CELEBRITY = 'ADD_CELEBRITY'
const ADD_CELEBRITIES = 'ADD_CELEBRITIES'
const ADD_CITIES = 'ADD_CITIES'
const SET_IS_FETCHING = 'SET_IS_FETCHING'
const SET_MOVIE_FETCH_STATUS = 'SET_MOVIE_FETCH_STATUS'
const SET_CELEBRITY_FETCH_STATUS = 'SET_CELEBRITY_FETCH_STATUS'
const SET_CITIES_FETCH_STATUS = 'SET_CITIES_FETCH_STATUS'
const SET_CURRENT_CITY = 'SET_CURRENT_CITY'

export { 
    ADD_MOVIE, 
    ADD_MOVIES, 
    ADD_CELEBRITY,
    ADD_CELEBRITIES,
    ADD_CITIES,
    SET_IS_FETCHING,
    SET_MOVIE_FETCH_STATUS,
    SET_CELEBRITY_FETCH_STATUS,
    SET_CITIES_FETCH_STATUS,
    SET_CURRENT_CITY,
}